version: "3.7"

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq

  app:
    build: ./api
    container_name: fastapi
    ports:
      - 8000:8000
    depends_on:
      - rabbit

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbit
      - app
